In [32]:
import pandas as pd
import numpy as np
from sklearn import model_selection, linear_model
from sklearn.metrics import accuracy_score

data = pd.read_csv("athletes_sochi.txt")

data

,age,birthdate,gender,height,name,weight,gold_medals,silver_medals,bronze_medals,total_medals,sport,country
0,17,1996-04-12,Male,1.72,Aaron Blunck,68.0,0,0,0,0,Freestyle Skiing,United States
1,27,1986-05-14,Male,1.85,Aaron March,85.0,0,0,0,0,Snowboard,Italy
2,21,1992-06-30,Male,1.78,Abzal Azhgaliyev,68.0,0,0,0,0,Short Track,Kazakhstan
3,21,1992-05-25,Male,1.68,Abzal Rakimgaliev,NaN,0,0,0,0,Figure Skating,Kazakhstan
4,21,1992-07-30,Male,1.86,Adam Barwood,82.0,0,0,0,0,Alpine Skiing,New Zealand
...,...,...,...,...,...,...,...,...,...,...,...,...
2854,28,1985-06-14,Female,1.68,Zoe Gillings,65.0,0,0,0,0,Snowboard,Great Britain
2855,27,1986-07-31,Male,1.71,Zoltan Kelemen,NaN,0,0,0,0,Figure Skating,Romania
2856,22,1991-03-01,Male,1.76,Zongyang Jia,68.0,0,0,1,1,Freestyle Skiing,China
2857,19,1995-02-06,Female,1.58,Zsofia Konya,54.0,0,0,0,0,Short Track,Hungary
2858,23,1990-05-21,Female,NaN,Zuzana Stromkova,NaN,0,0,0,0,Freestyle Skiing,Slovakia

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2859 entries, 0 to 2858
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            2859 non-null   int64
 1   birthdate      2859 non-null   object
 2   gender         2859 non-null   object
 3   height         2720 non-null   float64
 4   name           2859 non-null   object
 5   weight         2481 non-null   float64
 6   gold_medals    2859 non-null   int64
 7   silver_medals  2859 non-null   int64
 8   bronze_medals  2859 non-null   int64
 9   total_medals   2859 non-null   int64
 10  sport          2859 non-null   object
 11  country        2859 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 268.2+ KB

In [34]:
data.dropna(inplace=True)
data["BMI"] = data_frame["weight"] / (data_frame["height"]**2)
data["gender"] = np.where(data["gender"] == 'Male', 0, 1)
data

,age,birthdate,gender,height,name,weight,gold_medals,silver_medals,bronze_medals,total_medals,sport,country,BMI
0,17,1996-04-12,0,1.72,Aaron Blunck,68.0,0,0,0,0,Freestyle Skiing,United States,22.985398
1,27,1986-05-14,0,1.85,Aaron March,85.0,0,0,0,0,Snowboard,Italy,24.835646
2,21,1992-06-30,0,1.78,Abzal Azhgaliyev,68.0,0,0,0,0,Short Track,Kazakhstan,21.461937
4,21,1992-07-30,0,1.86,Adam Barwood,82.0,0,0,0,0,Alpine Skiing,New Zealand,23.702162
5,21,1992-12-18,0,1.75,Adam Cieslar,57.0,0,0,0,0,Nordic Combined,Poland,18.612245
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2851,28,1985-04-30,0,1.93,Ziga Pavlin,98.0,0,0,0,0,Ice Hockey,Slovenia,26.309431
2853,31,1982-12-05,1,1.70,Zina Kocher,60.0,0,0,0,0,Biathlon,Canada,20.761246
2854,28,1985-06-14,1,1.68,Zoe Gillings,65.0,0,0,0,0,Snowboard,Great Britain,23.030045
2856,22,1991-03-01,0,1.76,Zongyang Jia,68.0,0,0,1,1,Freestyle Skiing,China,21.952479
2857,19,1995-02-06,1,1.58,Zsofia Konya,54.0,0,0,0,0,Short Track,Hungary,21.631149

In [46]:
features1 = ["weight", "height"]
features2 = ["weight", "height", "total_medals"]
features3 = ["weight", "height", "BMI"]
features4 = ["BMI"]
features5 = ["total_medals", "BMI"]
features6 = ["weight", "height", "total_medals", "BMI"]
target = "gender"

def compute_accuracy(data, features, target):
    inputs = data[features]
    outputs = data[target]

    x_train, x_test, y_train, y_test = model_selection.train_test_split(inputs, outputs, test_size=0.3)
    
    logistic_model = linear_model.LogisticRegression()
    logistic_model.fit(x_train, y_train)
    
    y_pred = logistic_model.predict(x_test)
    
    return accuracy_score(y_test, y_pred)

print(f"Accuracy {features1}: ", round(compute_accuracy(data, features1, target), 2))
print(f"Accuracy {features2}: ", round(compute_accuracy(data, features2, target), 2))
print(f"Accuracy {features3}: ", round(compute_accuracy(data, features3, target), 2))
print(f"Accuracy {features4}: ", round(compute_accuracy(data, features4, target), 2))
print(f"Accuracy {features5}: ", round(compute_accuracy(data, features5, target), 2))
print(f"Accuracy {features6}: ", round(compute_accuracy(data, features6, target), 2))

Accuracy ['weight', 'height']:  0.85
Accuracy ['weight', 'height', 'total_medals']:  0.85
Accuracy ['weight', 'height', 'BMI']:  0.86
Accuracy ['BMI']:  0.75
Accuracy ['total_medals', 'BMI']:  0.73
Accuracy ['weight', 'height', 'total_medals', 'BMI']:  0.84